<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ERDTModel" nsURI="http://www.eclipse.org/sirius/sample/ERDTModel"
    nsPrefix="ERDTModel">
  <eClassifiers xsi:type="ecore:EClass" name="EntitySet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="has_attribute" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="has_interface" upperBound="-1"
        eType="#//Interface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueset" lowerBound="1"
        eType="#//ValueSet"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="has_parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" upperBound="-1"
        eType="#//OutgoingDataFlow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returns" upperBound="-1"
        eType="#//ReturnValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="is_of_type" eType="#//ValueSet"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncomingDataFlow" eSuperTypes="#//IncomingEvent #//DataRequest">
    <eStructuralFeatures xsi:type="ecore:EReference" name="user_interface" upperBound="-1"
        eType="#//Interface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncomingEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataRequest"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutgoingDataFlow" eSuperTypes="#//OutgoingEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutgoingEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="is_of_type" eType="#//ValueSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalTwin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entitysets" upperBound="-1"
        eType="#//EntitySet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueset" upperBound="-1"
        eType="#//ValueSet" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
